{{- if .Values.logs.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-onboarding-bot-logs
  namespace: {{ .Values.namespace }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- with .Values.logs.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.logs.persistence.size }}
{{- end }}
