{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ark-onboarding-bot
  namespace: {{ .Values.namespace }}
  {{- with .Values.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ . }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
